server:
  port: 8080
spring:
  application:
    name: product-service
  cloud:
    config:
      import-check:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka     